reidstivers/babysitters_club

- Gemfile
- Gemfile.lock
- config/initializers/devise.rb
- config/locales/devise.en.yml
Added the devise gem, bundle installed, and rails g devise:install
We need to proceed to the user
> Finish Devise Installation

- app/models/user.rb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/routes.rb
- db/migrate/20240713070210_devise_create_users.rb
- db/schema.rb
- test/models/user_test.rb
We went through the manual configuration by adding the line of code given in the lecture to development.rb
we checked if the root was set and it seemed to be so we didn't make any changes there
we added the default flash messages to application.html.erb
we skipped the initializer on the advice of Dillon
we generated the user with devise and ran db:migrate
> we created users with devise and migrated

- app/controllers/bookings_controller.rb
- app/controllers/listings_controller.rb
- app/models/booking.rb
- app/models/listing.rb
- config/routes.rb
- db/migrate/20240713073211_create_listings.rb
- db/migrate/20240713073712_create_bookings.rb
- db/schema.rb
- test/controllers/bookings_controller_test.rb
- test/controllers/listings_controller_test.rb
- test/models/booking_test.rb
- test/models/listing_test.rb
Created the booking and listing models, as well as several of the visws and a basic resources routes
> Model Creation

- app/controllers/application_controller.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- config/initializers/devise.rb
- db/migrate/20240713084805_add_names_to_users.rb
- db/schema.rb
added first and last name to the sign up realized we had no names in the user model and migrated a new one
also added strong params for names
also changed the head to a capital S in sitters
> Making a signup page

- app/controllers/listings_controller.rb
@rachel-schlaifer 
I only added index and show in listings_controller.rb since we need seeded data.
> index and show method are added to listings_controller.rb

- app/controllers/application_controller.rb
- app/models/booking.rb
- app/models/listing.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- db/migrate/20240716105631_add_location_to_users.rb
- db/migrate/20240716105944_add_location_tolisting.rb
- db/migrate/20240716112235_add_location_to_listings.rb
- db/schema.rb
Added validatations to the models for presence, as well as a minimum length for listing description
I've also added the locations field to user and listings, and updated the devise form accordingly.
Had to correct a migration error I had created as well, seems to be fine now.
> Model Update

- app/controllers/bookings_controller.rb
- app/models/listing.rb
Built up the bookings controller.
Because this controller refers to both user and listing, I'm not sure I've one it correctly. Might need some troubleshooting yet.
Also updated a variable error in the listing
> Build bookings controller

- app/controllers/listings_controller.rb
- app/views/listings/index.html.erb
I added items for listings for testing purposes.
Also, fixed listings_controller.rb > strong_param > price -> fee
I think we forgot to fixed it in the prior pull request.
> Listings index page - basic items added

- app/controllers/bookings_controller.rb
- app/controllers/listings_controller.rb
- app/views/listings/new.html.erb
- app/views/shared/_navbar.html.erb
Went through and added links to the navbar and created a working listing new page
some other small changes:
- added a comma to the navbar so it didn't display the class in the address bar
- redirected home and logo to the root
- added user to the listing create to get the new page working
- created a index page for bookings (not working details below)
current issues:
- the my bookings page shows everyone's bookings across the site
- the my listing page isn't coded at all
> created a listing new and edited navbar

- app/assets/stylesheets/config/_fonts.scss
I changed the header and body fonts to "Alumni Sans" which we used in Figma frameworks.
> Changed the fonts to "Alumni Sans"

- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/listings_controller.rb
- app/models/user.rb
- app/views/bookings/index.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/listings/index.html.erb
- app/views/shared/_navbar.html.erb
- db/migrate/20240717130711_add_photo_to_users.rb
- db/migrate/20240717131149_create_active_storage_tables.active_storage.rb
- db/schema.rb
Did a number of things
1. Added a photo field to the User Model (required migrations and code that auto-updated the schema and active storage tables)
2. Added a photo uploader to the user sign up (optional)
3. Created a path in the navbar dropdown to update the current user profile (this was already coded in devise, just made the route to it and added a photo field)
4. Coded the bookings index to only show bookings that have the current user id associated
5. Added cards to bookings / listing indexes because my lizard brain needed to separate the text
6. Added some spaces between methods in controllers as I was coding, just for readability's sake
7. Coded the navbar to replace the avatar with the photo of the user, if there is one
> General Updates

- app/controllers/listings_controller.rb
- app/models/listing.rb
- app/views/listings/index.html.erb
- app/views/listings/new.html.erb
- db/migrate/20240718073841_add_photos_to_listings.rb
- db/schema.rb
- db/seeds.rb
It took more doing than I expected cause working with photos is surprisingly difficult.
I don't believe Heroku supports photos this way and we will likely need to set up Cloudinary later on. That might be something to figure out on Saturday.
For now, I think it's enough to help us build the pages.
> photos field added to Listing and the Faker seed

- app/views/listings/show.html.erb
> added notes to booking

- .gitignore
- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
> Adding cloud

- app/assets/stylesheets/components/_booking_card.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/bookings_controller.rb
- app/views/bookings/show.html.erb
Coded the booking show page displaying the user's currently viewed booking details in a nice card. Added buttons to navigate back to the listings index or bookings index. 
Will work on styling and photos next!
> booking show page

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_listings_card.scss
- app/views/listings/index.html.erb
- db/seeds.rb
I added some styles to the listings index.
> First styling attempt to listings index

- app/views/listings/show.html.erb
just edited the listing show to add a link and a photo not super pretty yet
> added some small changes to the listing show

- Gemfile
- Gemfile.lock
- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/views/listings/show.html.erb
Add time validations to bookings, which required the installation of the Timeliness gem
Made some minor changes to the booking show
mostly just ended up wasting time sorting out bugs
> Refining booking journey

- app/views/bookings/index.html.erb
> added clickable cards

- app/assets/stylesheets/components/_listings_card.scss
- app/views/listings/index.html.erb
I made some changes to the card layout in listings/index. I think it has a better css now.
> fixed some css for listings card

- app/views/listings/index.html.erb
listings index wouldn't load till I removed one extra attached on line 26 otherwise it looks nicer for sure!
> extra attached in the listing index removed

- app/assets/stylesheets/components/_listings_card.scss
- app/views/listings/index.html.erb
I've set the coordinates of a listing image and applied to index.html.erb.
> listings index picture now has a set width

- app/models/user.rb
- app/views/listings/index.html.erb
User photos are working
resized them on listing index to match to match the default image
cleaned up some coding to make it more streamlined under Dillion
> Fixing photos

- app/views/bookings/show.html.erb
- app/views/listings/show.html.erb
- db/migrate/20240720022330_change_date_to_date_time_in_bookings.rb
- db/schema.rb
Changed the bookings show image
> Listings show

- app/views/bookings/show.html.erb
Before making any css changes to bookins/show page, I'd like to merge the page with the woking buttons.
> working bookings/show page

- app/views/bookings/show.html.erb
- app/views/listings/show.html.erb
Changed the new booking form to be a calendar picker.
> Added calendar picker to booking form

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_booking_card.scss
- app/views/bookings/show.html.erb
- app/views/listings/index.html.erb
Basic layout css is added to the page.
> bookings/show page. design added

- app/views/listings/show.html.erb
- db/schema.rb
I changed price font and format on the listing show page to display the price larger and more nicely
> Changed price font and format on the listing show page

- app/assets/stylesheets/components/_listing_card.scss
- app/views/listings/show.html.erb
fixed some layouts of the cards.
> layout changes

- app/assets/stylesheets/components/_booking_card.scss
- app/assets/stylesheets/components/_listing_card.scss
- app/views/listings/show.html.erb
> listing show

- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
I added pretty flashes based on Yann's Slack message. :)
> Added pretty flashes

- app/assets/stylesheets/components/_booking_card.scss
- app/assets/stylesheets/components/_listing_card.scss
- app/views/bookings/show.html.erb
- app/views/layouts/application.html.erb
- app/views/listings/show.html.erb
I made some css class name changes to avoid naming conflicts and fixed some css in bookings/show and listings/show.
Also, I commented out the <p> for flash messages in application.html.erb to avoid duplicate flash messages.
> CSS changes

- app/controllers/bookings_controller.rb
- app/controllers/listings_controller.rb
- app/views/bookings/index.html.erb
- app/views/listings/sitter_listings.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
I created a "View My Listings" page that will display all the listings for a current user. If there are no listings, the page shows a sad message asking the user if they want to create a listing and offer a service. 
I added this page under the Listings controller. But, it's not a listing index. It's something different, so I had to add a custom route. It seems much easier than creating a whole new controller and Sitter model. 
I also updated the booking controller index logic to display only the bookings for the signed in user (it previously displayed every booking in the database) and if the user has made no bookings, there is a message asking if they'd like to browse listings to book something.
> Created a "view my listings page" and updated logic in the bookings index. 

- Gemfile
- Gemfile.lock
- app/controllers/bookings_controller.rb
- app/controllers/listings_controller.rb
- app/models/listing.rb
- app/views/listings/index.html.erb
1. Added a gem (make sure you bundle install!)
2.  Added search bar to listings index. Coded it to take the name of the listing (case insenstive and even similar words), the description of the listing, and the sitter
> Search Bar

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_upcoming_bookings.scss
- app/controllers/application_controller.rb
- app/controllers/listings_controller.rb
- app/views/listings/show.html.erb
- app/views/listings/sitter_listings.html.erb
When viewing the listing show page as the owner of the listing, you can see your bookings associated with a listing! But, the container for viewing the form to make a booking got wonky and is no longer centered. :(
> Updated Sitter listings and listing show page 

- app/controllers/pages_controller.rb
Just added one line of code to whitelist the homepage.
> Whitelisted homepage

- app/controllers/bookings_controller.rb
- app/javascript/controllers/my-bookings_controller.js
- app/views/bookings/_list.html.erb
- app/views/bookings/index.html.erb
1. cleaned up some unneeded code that was there for debugging
2. Implemented a second JS controller for Bookings with Me
3. Got the filters working for this list
Next up, a toggle page!
> Super bookings

- app/controllers/application_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- db/migrate/20240725120145_add_qualification_to_users.rb
- db/schema.rb
I added the qualification text column to the User model, then added input to create user and edit user. 
I will work on show the qualification in listings/show before or on Saturday.
> Qualification added to User model

- app/views/listings/show.html.erb
Made bookings clickable on the listing show page
> Made bookings clickable on the listing show page 

- app/controllers/bookings_controller.rb
- app/javascript/controllers/bookings-pages_controller.js
- app/javascript/controllers/toggler_controller.js
- app/models/booking.rb
- app/views/bookings/_bookings_filter.html.erb
- app/views/bookings/_list.html.erb
- app/views/bookings/_my_bookings_filter.html.erb
- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- config/application.rb
- db/migrate/20240726013144_add_comments_to_bookings.rb
- db/migrate/20240726022921_add_fee_to_bookings.rb
- db/schema.rb
Here's what I did
1. Created another stimulus controller to handle a new toggle
2. Created 2 new partials in the views, one to handle My Bookings and one to handle Bookings With Me
3. Created buttons to display one partial or the other
4. Wrestled with god to fix the Javascript
5. Made it so the index ALWAYS displayed My Bookings (and not Bookings with Me) when opened
6. Hid the buttons to switch from My Bookings to Bookings with Me if the user does not have any listings
7. Cried a little bit once all this logic finally went through
8. Added an alert message to the Decline button on a booking
9. Created an option for a booking to cancel a confirmed booking
10. Added a button to mark a booking as complete
11. Cleaned up the Booking Show HTML to make it DRYer
12. Had a fistfight with a …
> Super Super Bookings!

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_pink_button.scss
- app/assets/stylesheets/components/_reviews_container.scss
- app/views/listings/new.html.erb
- app/views/listings/show.html.erb
I made styling changes the create a listing page and listing show page. I added qualifications to the listing show page and added an area for displaying reviews. I wanted to save these styling changes before I start messing with adding reviews to our models.
> Worked on the Listing Show Page 

- app/assets/stylesheets/components/_booking_card.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/bookings/_bookings_filter.html.erb
- app/views/bookings/_my_bookings_filter.html.erb
I added the new colors to the filter buttons. The colors are all controlled in _colors.scss now, so we can easily change the color later.
> button color scheme added

- app/assets/stylesheets/components/_reviews_container.scss
- app/controllers/bookings_controller.rb
- app/controllers/reviews_controller.rb
- app/models/booking.rb
- app/models/listing.rb
- app/models/review.rb
- app/models/user.rb
- app/views/bookings/show.html.erb
- app/views/listings/show.html.erb
- app/views/reviews/new.html.erb
- config/routes.rb
- db/migrate/20240727035229_create_reviews.rb
- db/migrate/20240727041507_add_user_to_reviews.rb
- db/schema.rb
- test/controllers/reviews_controller_test.rb
- test/models/review_test.rb
Created Reviews Model and users can now add a review on a booking that they created for a review. The review will display at the bottom of the listing show page associated with that booking.
> Reviews Model added

- app/assets/stylesheets/components/_listing_card.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/listings/_popup.html.erb
- app/views/shared/_navbar.html.erb
Just did a couple odd things to try to make it look nicer, couldn't get very far!
> Small Fixes

- app/views/bookings/_bookings_filter.html.erb
small fixes on the create a new listing button on listings page
> add style to create a new listing btn
